variables:
# This file is a template, and might need editing before it works on your project.
# TEST_NAME: registry.gitlab.com/daniel175/production-strategy-platform:latest
# TARGET_DIR: /Users/danielschrader/Desktop/Build2/$CI_PROJECT_NAME
# TEST_NAME: registry.gitlab.com/daniel175/production-strategy-platform:$CI_COMMIT_REF_NAME

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

stages:
  - publish
  - deploy

publish:
    image: node:20
    stage: publish
    artifacts:
        - build/
        - src/
    script:
        - yarn install
        - yarn build
        - echo "$PWD"
        - echo *
    only:
        - master
    #when: manual
    ## manually deploy ^^
    tags:
        - production
deploy:
    image: alpine:latest
    stage: deploy
    tags:
        - deployment
    script:
        ##- 'command -v ssh-agent >/dev/null || ( apk add --update openssh )' 
        ##- eval $(ssh-agent -s)
        ##
        ## Give the right permissions, otherwise ssh-add will refuse to add files
        ## Add the SSH key stored in SSH_PRIVATE_KEY file type CI/CD variable to the agent store
        ##
        - echo "$SchraderLaptop" > "SchraderLaptop.pem"
        - chmod 600 SchraderLaptop.pem
        - apk update && apk add openssh rsync
        ##- chmod 400 "$SchraderLaptop"
        ##- ssh-add "$SchraderLaptop"
        ##
        ## Create the SSH directory and give it the right permissions
        ##
        ##- mkdir -p ~/.ssh
        ##- chmod 700 ~/.ssh
        ##- echo -e "$DEPLOY_RSA" | tr -d '\r' | ssh-add -
        ##- ssh-keyscan 13.211.38.119 >> ~/.ssh/known_hosts
        ##- chmod 644 ~/.ssh/known_hosts
        ##
        - ssh -tt -i "SchraderLaptop.pem" -o StrictHostKeyChecking=no ec2-user@13.211.38.119 "hostname && echo 'Welcome!!!' > welcome.txt"
        - echo "Deploying to Production..."
        - echo "$PWD"
        - echo *
        - rsync -e "ssh -i SchraderLaptop.pem" -ru --delete ./ ec2-user@13.211.38.119:/home/ec2-user/strategyserver/
        - rsync -e "ssh -i SchraderLaptop.pem" -ru --delete ./src/emailtemplates ec2-user@13.211.38.119:/home/ec2-user/strategyserver/dist/
        - rsync -e "ssh -i SchraderLaptop.pem" -ru --delete ./src/files ec2-user@13.211.38.119:/home/ec2-user/strategyserver/dist/
        #send build to production folder and restart service with environment variables - add new prod env variables here:
        - ssh -i SchraderLaptop.pem -T ec2-user@13.211.38.119 -v "cd /home/ec2-user/strategyserver/ && PAYMENT_API_ENV='$PAYMENT_API_ENV' PAYMENT_API_KEY='$PAYMENT_API_KEY' PAYMENT_API_PASS='$PAYMENT_API_PASS' PAYMENT_MONTHLY_COST='$PAYMENT_MONTHLY_COST' PAYMENT_REDIRECT_URL='$PAYMENT_REDIRECT_URL' COPY_WHEELOFLIFE='$COPY_WHEELOFLIFE' NOTIFICATION_EMAIL='$NOTIFICATION_EMAIL' FEEDBACK_EMAIL='$FEEDBACK_EMAIL' MONGODB_URL='$MONGODB_URL' MONGODB_DB='$MONGODB_DB' MONGODB_USR='$MONGODB_USR' MONGODB_PWD='$MONGODB_PWD' GOOGLE_CLIENTID='$GOOGLE_CLIENTID' PATH_URL='$PATH_URL' EMAILCLIENT_USR='$EMAILCLIENT_USR' AWS_ACCESS_KEY_ID='$AWS_ACCESS_KEY_ID' AWS_SECRET_ACCESS_KEY='$AWS_SECRET_ACCESS_KEY' AWS_DEFAULT_REGION='$AWS_DEFAULT_REGION' AWS_BUCKET='$AWS_BUCKET' REDIS_DB='$REDIS_DB' pm2 restart index --update-env"
        - echo "new version placed on server and started"
    only:
        - master
    #when: manual
    ## manually deploy ^^
    tags:
        - production

    