variables:
# This file is a template, and might need editing before it works on your project.
# TEST_NAME: registry.gitlab.com/daniel175/production-strategy-platform:latest
# TARGET_DIR: /Users/danielschrader/Desktop/Build2/$CI_PROJECT_NAME
# TEST_NAME: registry.gitlab.com/daniel175/production-strategy-platform:$CI_COMMIT_REF_NAME

stages:
    - deploy

deploy:
    stage: deploy
    image: node:20
    before_script:
        - npm install
        - npm build
        #- sudo rsync -r --delete ./public/ ~/Desktop/Build/production
    script:
        - echo "Deploying to Production..."
        - rsync -ru --delete ./ ec2-user@13.211.38.119:/home/ec2-user/strategyserver/
        - rsync -ru --delete ./src/emailtemplates ec2-user@13.211.38.119:/home/ec2-user/strategyserver/dist/
        - rsync -ru --delete ./src/files ec2-user@13.211.38.119:/home/ec2-user/strategyserver/dist/
        #send build to production folder and restart service with environment variables - add new prod env variables here:
        - ssh -T ec2-user@13.211.38.119 -v "cd /home/ec2-user/strategyserver/ && PAYMENT_API_ENV='$PAYMENT_API_ENV' PAYMENT_API_KEY='$PAYMENT_API_KEY' PAYMENT_API_PASS='$PAYMENT_API_PASS' PAYMENT_MONTHLY_COST='$PAYMENT_MONTHLY_COST' PAYMENT_REDIRECT_URL='$PAYMENT_REDIRECT_URL' COPY_WHEELOFLIFE='$COPY_WHEELOFLIFE' NOTIFICATION_EMAIL='$NOTIFICATION_EMAIL' FEEDBACK_EMAIL='$FEEDBACK_EMAIL' MONGODB_URL='$MONGODB_URL' MONGODB_DB='$MONGODB_DB' MONGODB_USR='$MONGODB_USR' MONGODB_PWD='$MONGODB_PWD' GOOGLE_CLIENTID='$GOOGLE_CLIENTID' PATH_URL='$PATH_URL' EMAILCLIENT_USR='$EMAILCLIENT_USR' AWS_ACCESS_KEY_ID='$AWS_ACCESS_KEY_ID' AWS_SECRET_ACCESS_KEY='$AWS_SECRET_ACCESS_KEY' AWS_DEFAULT_REGION='$AWS_DEFAULT_REGION' AWS_BUCKET='$AWS_BUCKET' REDIS_DB='$REDIS_DB' pm2 restart index --update-env"
        - echo "new version placed on server and started"
    only:
        - master
    #when: manual
    ## manually deploy ^^
    tags:
        - production
